/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppPromisesRouteImport } from './routes/_authenticated/app.promises'
import { Route as AuthenticatedAppMemoryRouteImport } from './routes/_authenticated/app.memory'
import { Route as AuthenticatedAppLinkRouteImport } from './routes/_authenticated/app.link'
import { Route as AuthenticatedAppCommandRouteImport } from './routes/_authenticated/app.command'
import { Route as AuthenticatedAppCaptureRouteImport } from './routes/_authenticated/app.capture'
import { Route as AuthenticatedAdminWaitlistRouteImport } from './routes/_authenticated/admin.waitlist'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminOpsRouteImport } from './routes/_authenticated/admin.ops'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin.ingestion'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicIngestSessionStartRouteImport } from './routes/api/public/ingest/session-start'
import { Route as ApiPublicIngestSessionEndRouteImport } from './routes/api/public/ingest/session-end'
import { Route as ApiPublicIngestScreenFrameRouteImport } from './routes/api/public/ingest/screen-frame'
import { Route as ApiPublicIngestAudioChunkRouteImport } from './routes/api/public/ingest/audio-chunk'
import { Route as ApiPublicHooksSyncAllRouteImport } from './routes/api/public/hooks/sync-all'
import { Route as ApiPublicHooksGenerateRemindersRouteImport } from './routes/api/public/hooks/generate-reminders'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'
import { Route as ApiPublicExtensionTranscribeRouteImport } from './routes/api/public/extension/transcribe'
import { Route as ApiPublicExtensionTodayRouteImport } from './routes/api/public/extension/today'
import { Route as ApiPublicExtensionCaptureRouteImport } from './routes/api/public/extension/capture'
import { Route as ApiPublicAuthDeviceStartRouteImport } from './routes/api/public/auth/device-start'
import { Route as ApiPublicAuthDevicePollRouteImport } from './routes/api/public/auth/device-poll'
import { Route as ApiOauthGoogleCallbackRouteImport } from './routes/api/oauth.google.callback'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPromisesRoute =
  AuthenticatedAppPromisesRouteImport.update({
    id: '/promises',
    path: '/promises',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMemoryRoute = AuthenticatedAppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLinkRoute = AuthenticatedAppLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCommandRoute = AuthenticatedAppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCaptureRoute = AuthenticatedAppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminWaitlistRoute =
  AuthenticatedAdminWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOpsRoute = AuthenticatedAdminOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/ingestion',
    path: '/ingestion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestSessionStartRoute =
  ApiPublicIngestSessionStartRouteImport.update({
    id: '/api/public/ingest/session-start',
    path: '/api/public/ingest/session-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestSessionEndRoute =
  ApiPublicIngestSessionEndRouteImport.update({
    id: '/api/public/ingest/session-end',
    path: '/api/public/ingest/session-end',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestScreenFrameRoute =
  ApiPublicIngestScreenFrameRouteImport.update({
    id: '/api/public/ingest/screen-frame',
    path: '/api/public/ingest/screen-frame',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestAudioChunkRoute =
  ApiPublicIngestAudioChunkRouteImport.update({
    id: '/api/public/ingest/audio-chunk',
    path: '/api/public/ingest/audio-chunk',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncAllRoute = ApiPublicHooksSyncAllRouteImport.update({
  id: '/api/public/hooks/sync-all',
  path: '/api/public/hooks/sync-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateRemindersRoute =
  ApiPublicHooksGenerateRemindersRouteImport.update({
    id: '/api/public/hooks/generate-reminders',
    path: '/api/public/hooks/generate-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionTranscribeRoute =
  ApiPublicExtensionTranscribeRouteImport.update({
    id: '/api/public/extension/transcribe',
    path: '/api/public/extension/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionTodayRoute = ApiPublicExtensionTodayRouteImport.update({
  id: '/api/public/extension/today',
  path: '/api/public/extension/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionCaptureRoute =
  ApiPublicExtensionCaptureRouteImport.update({
    id: '/api/public/extension/capture',
    path: '/api/public/extension/capture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDeviceStartRoute =
  ApiPublicAuthDeviceStartRouteImport.update({
    id: '/api/public/auth/device-start',
    path: '/api/public/auth/device-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthDevicePollRoute = ApiPublicAuthDevicePollRouteImport.update({
  id: '/api/public/auth/device-poll',
  path: '/api/public/auth/device-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthGoogleCallbackRoute = ApiOauthGoogleCallbackRouteImport.update({
  id: '/api/oauth/google/callback',
  path: '/api/oauth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/ops': typeof AuthenticatedAdminOpsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/app/capture': typeof AuthenticatedAppCaptureRoute
  '/app/command': typeof AuthenticatedAppCommandRoute
  '/app/link': typeof AuthenticatedAppLinkRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/promises': typeof AuthenticatedAppPromisesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/auth/device-poll': typeof ApiPublicAuthDevicePollRoute
  '/api/public/auth/device-start': typeof ApiPublicAuthDeviceStartRoute
  '/api/public/extension/capture': typeof ApiPublicExtensionCaptureRoute
  '/api/public/extension/today': typeof ApiPublicExtensionTodayRoute
  '/api/public/extension/transcribe': typeof ApiPublicExtensionTranscribeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/generate-reminders': typeof ApiPublicHooksGenerateRemindersRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ingest/audio-chunk': typeof ApiPublicIngestAudioChunkRoute
  '/api/public/ingest/screen-frame': typeof ApiPublicIngestScreenFrameRoute
  '/api/public/ingest/session-end': typeof ApiPublicIngestSessionEndRoute
  '/api/public/ingest/session-start': typeof ApiPublicIngestSessionStartRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/ops': typeof AuthenticatedAdminOpsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/app/capture': typeof AuthenticatedAppCaptureRoute
  '/app/command': typeof AuthenticatedAppCommandRoute
  '/app/link': typeof AuthenticatedAppLinkRoute
  '/app/memory': typeof AuthenticatedAppMemoryRoute
  '/app/promises': typeof AuthenticatedAppPromisesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/auth/device-poll': typeof ApiPublicAuthDevicePollRoute
  '/api/public/auth/device-start': typeof ApiPublicAuthDeviceStartRoute
  '/api/public/extension/capture': typeof ApiPublicExtensionCaptureRoute
  '/api/public/extension/today': typeof ApiPublicExtensionTodayRoute
  '/api/public/extension/transcribe': typeof ApiPublicExtensionTranscribeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/generate-reminders': typeof ApiPublicHooksGenerateRemindersRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ingest/audio-chunk': typeof ApiPublicIngestAudioChunkRoute
  '/api/public/ingest/screen-frame': typeof ApiPublicIngestScreenFrameRoute
  '/api/public/ingest/session-end': typeof ApiPublicIngestSessionEndRoute
  '/api/public/ingest/session-start': typeof ApiPublicIngestSessionStartRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/founder': typeof FounderRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/ops': typeof AuthenticatedAdminOpsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/waitlist': typeof AuthenticatedAdminWaitlistRoute
  '/_authenticated/app/capture': typeof AuthenticatedAppCaptureRoute
  '/_authenticated/app/command': typeof AuthenticatedAppCommandRoute
  '/_authenticated/app/link': typeof AuthenticatedAppLinkRoute
  '/_authenticated/app/memory': typeof AuthenticatedAppMemoryRoute
  '/_authenticated/app/promises': typeof AuthenticatedAppPromisesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/oauth/google/callback': typeof ApiOauthGoogleCallbackRoute
  '/api/public/auth/device-poll': typeof ApiPublicAuthDevicePollRoute
  '/api/public/auth/device-start': typeof ApiPublicAuthDeviceStartRoute
  '/api/public/extension/capture': typeof ApiPublicExtensionCaptureRoute
  '/api/public/extension/today': typeof ApiPublicExtensionTodayRoute
  '/api/public/extension/transcribe': typeof ApiPublicExtensionTranscribeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/generate-reminders': typeof ApiPublicHooksGenerateRemindersRoute
  '/api/public/hooks/sync-all': typeof ApiPublicHooksSyncAllRoute
  '/api/public/ingest/audio-chunk': typeof ApiPublicIngestAudioChunkRoute
  '/api/public/ingest/screen-frame': typeof ApiPublicIngestScreenFrameRoute
  '/api/public/ingest/session-end': typeof ApiPublicIngestSessionEndRoute
  '/api/public/ingest/session-start': typeof ApiPublicIngestSessionStartRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/try'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/api/agent'
    | '/api/chat'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin/events'
    | '/admin/ingestion'
    | '/admin/ops'
    | '/admin/users'
    | '/admin/waitlist'
    | '/app/capture'
    | '/app/command'
    | '/app/link'
    | '/app/memory'
    | '/app/promises'
    | '/app/settings'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/app/'
    | '/api/oauth/google/callback'
    | '/api/public/auth/device-poll'
    | '/api/public/auth/device-start'
    | '/api/public/extension/capture'
    | '/api/public/extension/today'
    | '/api/public/extension/transcribe'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/generate-reminders'
    | '/api/public/hooks/sync-all'
    | '/api/public/ingest/audio-chunk'
    | '/api/public/ingest/screen-frame'
    | '/api/public/ingest/session-end'
    | '/api/public/ingest/session-start'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/try'
    | '/onboarding'
    | '/api/agent'
    | '/api/chat'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin/events'
    | '/admin/ingestion'
    | '/admin/ops'
    | '/admin/users'
    | '/admin/waitlist'
    | '/app/capture'
    | '/app/command'
    | '/app/link'
    | '/app/memory'
    | '/app/promises'
    | '/app/settings'
    | '/lovable/email/suppression'
    | '/admin'
    | '/app'
    | '/api/oauth/google/callback'
    | '/api/public/auth/device-poll'
    | '/api/public/auth/device-start'
    | '/api/public/extension/capture'
    | '/api/public/extension/today'
    | '/api/public/extension/transcribe'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/generate-reminders'
    | '/api/public/hooks/sync-all'
    | '/api/public/ingest/audio-chunk'
    | '/api/public/ingest/screen-frame'
    | '/api/public/ingest/session-end'
    | '/api/public/ingest/session-start'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agent'
    | '/auth'
    | '/founder'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/try'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/api/agent'
    | '/api/chat'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/ops'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/waitlist'
    | '/_authenticated/app/capture'
    | '/_authenticated/app/command'
    | '/_authenticated/app/link'
    | '/_authenticated/app/memory'
    | '/_authenticated/app/promises'
    | '/_authenticated/app/settings'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/api/oauth/google/callback'
    | '/api/public/auth/device-poll'
    | '/api/public/auth/device-start'
    | '/api/public/extension/capture'
    | '/api/public/extension/today'
    | '/api/public/extension/transcribe'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/generate-reminders'
    | '/api/public/hooks/sync-all'
    | '/api/public/ingest/audio-chunk'
    | '/api/public/ingest/screen-frame'
    | '/api/public/ingest/session-end'
    | '/api/public/ingest/session-start'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  FounderRoute: typeof FounderRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TryRoute: typeof TryRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiOauthGoogleCallbackRoute: typeof ApiOauthGoogleCallbackRoute
  ApiPublicAuthDevicePollRoute: typeof ApiPublicAuthDevicePollRoute
  ApiPublicAuthDeviceStartRoute: typeof ApiPublicAuthDeviceStartRoute
  ApiPublicExtensionCaptureRoute: typeof ApiPublicExtensionCaptureRoute
  ApiPublicExtensionTodayRoute: typeof ApiPublicExtensionTodayRoute
  ApiPublicExtensionTranscribeRoute: typeof ApiPublicExtensionTranscribeRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  ApiPublicHooksGenerateRemindersRoute: typeof ApiPublicHooksGenerateRemindersRoute
  ApiPublicHooksSyncAllRoute: typeof ApiPublicHooksSyncAllRoute
  ApiPublicIngestAudioChunkRoute: typeof ApiPublicIngestAudioChunkRoute
  ApiPublicIngestScreenFrameRoute: typeof ApiPublicIngestScreenFrameRoute
  ApiPublicIngestSessionEndRoute: typeof ApiPublicIngestSessionEndRoute
  ApiPublicIngestSessionStartRoute: typeof ApiPublicIngestSessionStartRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/promises': {
      id: '/_authenticated/app/promises'
      path: '/promises'
      fullPath: '/app/promises'
      preLoaderRoute: typeof AuthenticatedAppPromisesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/memory': {
      id: '/_authenticated/app/memory'
      path: '/memory'
      fullPath: '/app/memory'
      preLoaderRoute: typeof AuthenticatedAppMemoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/link': {
      id: '/_authenticated/app/link'
      path: '/link'
      fullPath: '/app/link'
      preLoaderRoute: typeof AuthenticatedAppLinkRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/command': {
      id: '/_authenticated/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AuthenticatedAppCommandRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/capture': {
      id: '/_authenticated/app/capture'
      path: '/capture'
      fullPath: '/app/capture'
      preLoaderRoute: typeof AuthenticatedAppCaptureRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/waitlist': {
      id: '/_authenticated/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AuthenticatedAdminWaitlistRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ops': {
      id: '/_authenticated/admin/ops'
      path: '/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AuthenticatedAdminOpsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/session-start': {
      id: '/api/public/ingest/session-start'
      path: '/api/public/ingest/session-start'
      fullPath: '/api/public/ingest/session-start'
      preLoaderRoute: typeof ApiPublicIngestSessionStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/session-end': {
      id: '/api/public/ingest/session-end'
      path: '/api/public/ingest/session-end'
      fullPath: '/api/public/ingest/session-end'
      preLoaderRoute: typeof ApiPublicIngestSessionEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/screen-frame': {
      id: '/api/public/ingest/screen-frame'
      path: '/api/public/ingest/screen-frame'
      fullPath: '/api/public/ingest/screen-frame'
      preLoaderRoute: typeof ApiPublicIngestScreenFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/audio-chunk': {
      id: '/api/public/ingest/audio-chunk'
      path: '/api/public/ingest/audio-chunk'
      fullPath: '/api/public/ingest/audio-chunk'
      preLoaderRoute: typeof ApiPublicIngestAudioChunkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-all': {
      id: '/api/public/hooks/sync-all'
      path: '/api/public/hooks/sync-all'
      fullPath: '/api/public/hooks/sync-all'
      preLoaderRoute: typeof ApiPublicHooksSyncAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-reminders': {
      id: '/api/public/hooks/generate-reminders'
      path: '/api/public/hooks/generate-reminders'
      fullPath: '/api/public/hooks/generate-reminders'
      preLoaderRoute: typeof ApiPublicHooksGenerateRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/transcribe': {
      id: '/api/public/extension/transcribe'
      path: '/api/public/extension/transcribe'
      fullPath: '/api/public/extension/transcribe'
      preLoaderRoute: typeof ApiPublicExtensionTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/today': {
      id: '/api/public/extension/today'
      path: '/api/public/extension/today'
      fullPath: '/api/public/extension/today'
      preLoaderRoute: typeof ApiPublicExtensionTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/capture': {
      id: '/api/public/extension/capture'
      path: '/api/public/extension/capture'
      fullPath: '/api/public/extension/capture'
      preLoaderRoute: typeof ApiPublicExtensionCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/device-start': {
      id: '/api/public/auth/device-start'
      path: '/api/public/auth/device-start'
      fullPath: '/api/public/auth/device-start'
      preLoaderRoute: typeof ApiPublicAuthDeviceStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/device-poll': {
      id: '/api/public/auth/device-poll'
      path: '/api/public/auth/device-poll'
      fullPath: '/api/public/auth/device-poll'
      preLoaderRoute: typeof ApiPublicAuthDevicePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/google/callback': {
      id: '/api/oauth/google/callback'
      path: '/api/oauth/google/callback'
      fullPath: '/api/oauth/google/callback'
      preLoaderRoute: typeof ApiOauthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminOpsRoute: typeof AuthenticatedAdminOpsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWaitlistRoute: typeof AuthenticatedAdminWaitlistRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
  AuthenticatedAdminOpsRoute: AuthenticatedAdminOpsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWaitlistRoute: AuthenticatedAdminWaitlistRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppCaptureRoute: typeof AuthenticatedAppCaptureRoute
  AuthenticatedAppCommandRoute: typeof AuthenticatedAppCommandRoute
  AuthenticatedAppLinkRoute: typeof AuthenticatedAppLinkRoute
  AuthenticatedAppMemoryRoute: typeof AuthenticatedAppMemoryRoute
  AuthenticatedAppPromisesRoute: typeof AuthenticatedAppPromisesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppCaptureRoute: AuthenticatedAppCaptureRoute,
  AuthenticatedAppCommandRoute: AuthenticatedAppCommandRoute,
  AuthenticatedAppLinkRoute: AuthenticatedAppLinkRoute,
  AuthenticatedAppMemoryRoute: AuthenticatedAppMemoryRoute,
  AuthenticatedAppPromisesRoute: AuthenticatedAppPromisesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  FounderRoute: FounderRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TryRoute: TryRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiOauthGoogleCallbackRoute: ApiOauthGoogleCallbackRoute,
  ApiPublicAuthDevicePollRoute: ApiPublicAuthDevicePollRoute,
  ApiPublicAuthDeviceStartRoute: ApiPublicAuthDeviceStartRoute,
  ApiPublicExtensionCaptureRoute: ApiPublicExtensionCaptureRoute,
  ApiPublicExtensionTodayRoute: ApiPublicExtensionTodayRoute,
  ApiPublicExtensionTranscribeRoute: ApiPublicExtensionTranscribeRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  ApiPublicHooksGenerateRemindersRoute: ApiPublicHooksGenerateRemindersRoute,
  ApiPublicHooksSyncAllRoute: ApiPublicHooksSyncAllRoute,
  ApiPublicIngestAudioChunkRoute: ApiPublicIngestAudioChunkRoute,
  ApiPublicIngestScreenFrameRoute: ApiPublicIngestScreenFrameRoute,
  ApiPublicIngestSessionEndRoute: ApiPublicIngestSessionEndRoute,
  ApiPublicIngestSessionStartRoute: ApiPublicIngestSessionStartRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
